services:
    backend:
        build: .
        container_name: mlops-backend
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://192.168.1.11:8000/v1/health"]
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 15s
        ports:
            - 8000:8000
        extra_hosts:
            - "localhost:0.0.0.0"