name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PEM_KEY }}
        script: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
          docker pull thuannan/fastapi-backend:latest
          docker stop fastapi-backend
          docker rm fastapi-backend
          docker run -d -p 80:8000 --name fastapi-backend thuannan/fastapi-backend:latest
